export default {
  CARD_BACK_BY_PLAYER           : 'CARD_BACK_BY_PLAYER'           ,
  CARD_MOVE_BY_ENGINE           : 'CARD_MOVE_BY_ENGINE'           ,
  CARD_MOVE_BY_PLAYER           : 'CARD_MOVE_BY_PLAYER'           ,
  CLOSE_RECORDS                 : 'CLOSE_RECORDS'                 ,
  CLOSE_RULES                   : 'CLOSE_RULES'                   ,
  CLOSE_OPTIONS                 : 'CLOSE_OPTIONS'                 ,
  CORE_CARD_BACK_BY_PLAYER      : 'CORE_CARD_BACK_BY_PLAYER'      ,
  CORE_CARD_FLIP_BY_ENGINE      : 'CORE_CARD_FLIP_BY_ENGINE'      ,
  CORE_CARD_MOVE_BY_ENGINE      : 'CORE_CARD_MOVE_BY_ENGINE'      ,
  CORE_CARD_MOVE_BY_PLAYER      : 'CORE_CARD_MOVE_BY_PLAYER'      ,
  FX_RESIZE                     : 'FX_RESIZE'                     ,
  GAME_CREATED                  : 'GAME_CREATED'                  , /** Сигнал о создании игры и начале раздачи карт */
  GAME_COMPLETE                 : 'GAME_COMPLETE'                 ,
  GAME_START                    : 'GAME_START'                    ,
  LOAD_SCENARIO                 : 'LOAD_SCENARIO'                 ,
  NEW_RECORD                    : 'NEW_RECORD'                    ,
  NOTHING                       : 'NOTHING'                       ,
  OPTIONS_TOGGLE_DND            : 'OPTIONS_TOGGLE_DND'            ,
  REVERT                        : 'REVERT'                        ,
  SHOW_RECORDS                  : 'SHOW_RECORDS'                  ,
  SHOW_RULES                    : 'SHOW_RULES'                    ,
  SHOW_OPTIONS                  : 'SHOW_OPTIONS'                  ,
  WEAK_RECORD                   : 'WEAK_RECORD'                   ,
};
