export default {
  LOAD_SCENARIO : 'LOAD_SCENARIO' ,
  NEW_RECORD    : 'NEW_RECORD'    ,
  WEAK_RECORD   : 'WEAK_RECORD'   ,
  NEW_GAME      : 'NEW_GAME'      ,
  GAME_END      : 'GAME_END'      ,
  WRITE_TURN    : 'WRITE_TURN'    ,
  TICK          : 'TICK'          ,
  REVERT        : 'REVERT'        ,
  CAN_COMPLETE  : 'CAN_COMPLETE'  ,
  CAN_SWAP      : 'CAN_SWAP'      ,
  OPEN_CARD     : 'OPEN_CARD'     ,
  STACK_TO_HOME : 'STACK_TO_HOME' ,
  OPEN_TO_HOME  : 'OPEN_TO_HOME'  ,
  DECK_TO_HOME  : 'DECK_TO_HOME'  ,
  LAY_TO_DECK   : 'LAY_TO_DECK'   ,
  LAY_TO_STACK  : 'LAY_TO_STACK'  ,
  LAY_TO_OPEN   : 'LAY_TO_OPEN'   ,
  GAME_START    : 'GAME_START'    ,
  DECK_SHOW     : 'DECK_SHOW'     ,
  CAN_NEW_GAME  : 'CAN_NEW_GAME'  ,
  SHOW_RECORDS  : 'SHOW_RECORDS'  ,
  CLOSE_RECORDS : 'CLOSE_RECORDS' ,
  SHOW_RULES    : 'SHOW_RULES'    ,
  CLOSE_RULES   : 'CLOSE_RULES'
};
