export default {
  CAN_COMPLETE          : 'CAN_COMPLETE'          ,
  CAN_NEW_GAME          : 'CAN_NEW_GAME'          ,
  CAN_SWAP              : 'CAN_SWAP'              ,
  CLOSE_ABOUT           : 'CLOSE_ABOUT'           ,
  CLOSE_RECORDS         : 'CLOSE_RECORDS'         ,
  CLOSE_RULES           : 'CLOSE_RULES'           ,
  DECK_SHOW             : 'DECK_SHOW'             ,
  DECK_TO_STACK         : 'DECK_TO_STACK'         , /** Служебное действие, не является ходом */
  DRAG_END_CARD         : 'DRAG_END_CARD'         ,
  DRAG_ENTER_CARD       : 'DRAG_ENTER_CARD'       ,
  DRAG_ENTER_HOME       : 'DRAG_ENTER_HOME'       ,
  DRAG_ENTER_STACK      : 'DRAG_ENTER_STACK'      ,
  DRAG_LEAVE_CARD       : 'DRAG_LEAVE_CARD'       ,
  DRAG_LEAVE_HOME       : 'DRAG_LEAVE_HOME'       ,
  DRAG_LEAVE_STACK      : 'DRAG_LEAVE_STACK'      ,
  GAME_END              : 'GAME_END'              ,
  GAME_START            : 'GAME_START'            ,
  HOME_TO_DECK          : 'HOME_TO_DECK'          , /** Дурацкое авто-действие в конце игры после закрытия рекордов */
  LOAD_SCENARIO         : 'LOAD_SCENARIO'         ,
  NEW_GAME              : 'NEW_GAME'              ,
  NEW_RECORD            : 'NEW_RECORD'            ,
  OPEN_CARD             : 'OPEN_CARD'             ,
  OPEN_TO_HOME          : 'OPEN_TO_HOME'          , /** А это уже реальный ход, с бэкапом доски и (TODO а объект "карта" бэкапится?!!!!) */
  REVERT                : 'REVERT'                ,
  SHOW_ABOUT            : 'SHOW_ABOUT'            ,
  SHOW_RECORDS          : 'SHOW_RECORDS'          ,
  SHOW_RULES            : 'SHOW_RULES'            ,
  STACK_TO_HOME         : 'STACK_TO_HOME'         ,
  TICK                  : 'TICK'                  ,
  WEAK_RECORD           : 'WEAK_RECORD'           ,
  WRITE_TURN            : 'WRITE_TURN'            ,
};
